name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./reserve/pom.xml
          mvn clean package -f ./movie/pom.xml
          mvn clean package -f ./reservelist/pom.xml
          mvn clean package -f ./notification/pom.xml

      - name: Docker Build and push for Reserve
        uses: docker/build-push-action@v4
        with:
          context: ./reserve
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reserve:latest
            ghcr.io/${{ github.repository }}/reserve:${{ github.ref_name }}
            
      - name: Docker Build and push for Movie
        uses: docker/build-push-action@v4
        with:
          context: ./movie
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/movie:latest
            ghcr.io/${{ github.repository }}/movie:${{ github.ref_name }}
            
      - name: Docker Build and push for Reservelist
        uses: docker/build-push-action@v4
        with:
          context: ./reservelist
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservelist:latest
            ghcr.io/${{ github.repository }}/reservelist:${{ github.ref_name }}
            
      - name: Docker Build and push for Notification
        uses: docker/build-push-action@v4
        with:
          context: ./notification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notification:latest
            ghcr.io/${{ github.repository }}/notification:${{ github.ref_name }}
            
