server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: reserve
          uri: http://localhost:8082
          predicates:
            - Path=/reserves/**, 
        - id: movie
          uri: http://localhost:8083
          predicates:
            - Path=/movies/**, 
        - id: reservelist
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/reserves/**, 
        - id: movie
          uri: http://movie:8080
          predicates:
            - Path=/movies/**, 
        - id: reservelist
          uri: http://reservelist:8080
          predicates:
            - Path=, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
