apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservelist
  labels:
    app: reservelist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservelist
  template:
    metadata:
      labels:
        app: reservelist
    spec:
      containers:
        - name: reservelist
          image: "username/reservelist:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
